#!/usr/bin/env python3
"""Builds the LecCheck icon font from design/icons/*.svg.

    uv run --with picosvg --with fonttools python design/build_icons.py

Icons are drawn on a 24px grid with 2px round strokes. picosvg converts the
strokes to filled outlines, the outlines become TrueType glyphs at Private Use
Area codepoints, and a Dart class with const IconData entries is generated so
Flutter can tree-shake the font.
"""

import pathlib
import re

from fontTools.fontBuilder import FontBuilder
from fontTools.pens.cu2quPen import Cu2QuPen
from fontTools.pens.transformPen import TransformPen
from fontTools.pens.ttGlyphPen import TTGlyphPen
from fontTools.svgLib.path import parse_path
from pathops import Path as SkPath
from pathops import PathOp, op
from picosvg.svg import SVG

ROOT = pathlib.Path(__file__).resolve().parent
ICONS = ROOT / "icons"
APP = ROOT.parent / "app"
FONT = APP / "assets" / "fonts" / "LecIcons.ttf"
DART = APP / "lib" / "core" / "icons" / "lec_icon_font.dart"

UPM = 960
SCALE = UPM / 24
FIRST_CODEPOINT = 0xE000


def glyph_for(svg_file: pathlib.Path):
    pico = SVG.parse(str(svg_file)).topicosvg()
    tt_pen = TTGlyphPen(None)
    # SVG y grows down, font y grows up: flip, then reverse contour direction
    # so outer contours stay clockwise as TrueType expects.
    pen = TransformPen(
        Cu2QuPen(tt_pen, max_err=0.5, reverse_direction=True),
        (SCALE, 0, 0, -SCALE, 0, UPM),
    )
    # Union every filled shape (fills + outlined strokes) with winding fixed,
    # so a fill drawn in the opposite direction to its stroke can't cancel out.
    shapes = []
    for shape in pico.shapes():
        sk = SkPath()
        parse_path(shape.as_path().d, sk.getPen())
        shapes.append(sk)
    # Pairwise boolean union evaluates each shape's own fill, unlike drawing
    # everything into one path (where opposite windings cancel to a hole).
    merged = shapes[0]
    for sk in shapes[1:]:
        merged = op(merged, sk, PathOp.UNION, fix_winding=True)
    merged.draw(pen)
    return tt_pen.glyph()


def camel(name: str) -> str:
    head, *rest = name.split("_")
    return head + "".join(part.capitalize() for part in rest)


def main() -> None:
    names = sorted(p.stem for p in ICONS.glob("*.svg"))
    order = [".notdef", *names]
    glyphs = {".notdef": TTGlyphPen(None).glyph()}
    cmap = {}
    for i, name in enumerate(names):
        glyphs[name] = glyph_for(ICONS / f"{name}.svg")
        cmap[FIRST_CODEPOINT + i] = name

    fb = FontBuilder(UPM, isTTF=True)
    fb.setupGlyphOrder(order)
    fb.setupCharacterMap(cmap)
    fb.setupGlyf(glyphs)
    glyf = fb.font["glyf"]
    fb.setupHorizontalMetrics(
        {n: (UPM, getattr(glyf[n], "xMin", 0)) for n in order}
    )
    fb.setupHorizontalHeader(ascent=UPM, descent=0)
    fb.setupNameTable({"familyName": "LecIcons", "styleName": "Regular"})
    fb.setupOS2(
        version=4,
        sTypoAscender=UPM,
        sTypoDescender=0,
        sTypoLineGap=0,
        usWinAscent=UPM,
        usWinDescent=0,
        fsSelection=0x40 | 0x80,  # REGULAR | USE_TYPO_METRICS
    )
    fb.setupPost()
    FONT.parent.mkdir(parents=True, exist_ok=True)
    fb.save(str(FONT))

    lines = [
        "// GENERATED by design/build_icons.py from design/icons/*.svg.",
        "// Do not edit by hand; add or change an SVG and re-run the script.",
        "import 'package:material_ui/material_ui.dart';",
        "",
        "/// Custom LecCheck glyphs (24px grid, 2px round strokes).",
        "abstract final class LecIconFont {",
        "  static const _family = 'LecIcons';",
        "",
    ]
    for code, name in sorted(cmap.items()):
        lines.append(
            f"  static const {camel(name)} = IconData(0x{code:x}, fontFamily: _family);"
        )
    lines.append("}")
    DART.write_text("\n".join(lines) + "\n")
    print(f"{len(names)} icons -> {FONT.relative_to(ROOT.parent)}, {DART.relative_to(ROOT.parent)}")


if __name__ == "__main__":
    main()
