// GENERATED by design/build_icons.py from design/icons/*.svg.
// Do not edit by hand; add or change an SVG and re-run the script.
import 'package:material_ui/material_ui.dart';

/// Custom LecCheck glyphs (24px grid, 2px round strokes).
abstract final class LecIconFont {
  static const _family = 'LecIcons';

  static const attended = IconData(0xe000, fontFamily: _family);
  static const canceled = IconData(0xe001, fontFamily: _family);
  static const courses = IconData(0xe002, fontFamily: _family);
  static const coursesFilled = IconData(0xe003, fontFamily: _family);
  static const holiday = IconData(0xe004, fontFamily: _family);
  static const lab = IconData(0xe005, fontFamily: _family);
  static const lecture = IconData(0xe006, fontFamily: _family);
  static const missed = IconData(0xe007, fontFamily: _family);
  static const moved = IconData(0xe008, fontFamily: _family);
  static const other = IconData(0xe009, fontFamily: _family);
  static const pending = IconData(0xe00a, fontFamily: _family);
  static const practice = IconData(0xe00b, fontFamily: _family);
  static const settings = IconData(0xe00c, fontFamily: _family);
  static const settingsFilled = IconData(0xe00d, fontFamily: _family);
  static const skipped = IconData(0xe00e, fontFamily: _family);
  static const stats = IconData(0xe00f, fontFamily: _family);
  static const statsFilled = IconData(0xe010, fontFamily: _family);
  static const streak = IconData(0xe011, fontFamily: _family);
  static const target = IconData(0xe012, fontFamily: _family);
  static const today = IconData(0xe013, fontFamily: _family);
  static const todayFilled = IconData(0xe014, fontFamily: _family);
  static const watched = IconData(0xe015, fontFamily: _family);
  static const week = IconData(0xe016, fontFamily: _family);
  static const weekFilled = IconData(0xe017, fontFamily: _family);
}
